import { Asset, Prefab, SpriteFrame, sp } from "cc"
import { loopFiles } from "../../../base/SourceManage"

export enum PokerSpriteFramePathDefine {
    P2B = "img/pokerNum/2B/spriteFrame",
    P2R = "img/pokerNum/2R/spriteFrame",
    P3B = "img/pokerNum/3B/spriteFrame",
    P3R = "img/pokerNum/3R/spriteFrame",
    P4B = "img/pokerNum/4B/spriteFrame",
    P4R = "img/pokerNum/4R/spriteFrame",
    P5B = "img/pokerNum/5B/spriteFrame",
    P5R = "img/pokerNum/5R/spriteFrame",
    P6B = "img/pokerNum/6B/spriteFrame",
    P6R = "img/pokerNum/6R/spriteFrame",
    P7B = "img/pokerNum/7B/spriteFrame",
    P7R = "img/pokerNum/7R/spriteFrame",
    P8B = "img/pokerNum/8B/spriteFrame",
    P8R = "img/pokerNum/8R/spriteFrame",
    P9B = "img/pokerNum/9B/spriteFrame",
    P9R = "img/pokerNum/9R/spriteFrame",
    P10B = "img/pokerNum/10B/spriteFrame",
    P10R = "img/pokerNum/10R/spriteFrame",
    PJB = "img/pokerNum/JB/spriteFrame",
    PJR = "img/pokerNum/JR/spriteFrame",
    PQB = "img/pokerNum/QB/spriteFrame",
    PQR = "img/pokerNum/QR/spriteFrame",
    PKB = "img/pokerNum/KB/spriteFrame",
    PKR = "img/pokerNum/KR/spriteFrame",
    PAB = "img/pokerNum/AB/spriteFrame",
    PAR = "img/pokerNum/AR/spriteFrame",
    DIAMOND_L = "img/pokerNum/fangkuai_l/spriteFrame",
    DIAMOND_S = "img/pokerNum/fangkuai_s/spriteFrame",
    SPADE_L = "img/pokerNum/heitao_l/spriteFrame",
    SPADE_S = "img/pokerNum/heitao_s/spriteFrame",
    HEART_L = "img/pokerNum/hongxin_l/spriteFrame",
    HEART_S = "img/pokerNum/hongxin_s/spriteFrame",
    CLUB_L = "img/pokerNum/meihua_l/spriteFrame",
    CLUB_S = "img/pokerNum/meihua_s/spriteFrame",
    J_TX_1 = "img/pokerNum/j1/spriteFrame",
    J_TX_2 = "img/pokerNum/j2/spriteFrame",
    J_TX_3 = "img/pokerNum/j3/spriteFrame",
    J_TX_4 = "img/pokerNum/j4/spriteFrame",
    Q_TX_1 = "img/pokerNum/q1/spriteFrame",
    Q_TX_2 = "img/pokerNum/q2/spriteFrame",
    Q_TX_3 = "img/pokerNum/q3/spriteFrame",
    Q_TX_4 = "img/pokerNum/q4/spriteFrame",
    K_TX_1 = "img/pokerNum/k1/spriteFrame",
    K_TX_2 = "img/pokerNum/k2/spriteFrame",
    K_TX_3 = "img/pokerNum/k3/spriteFrame",
    K_TX_4 = "img/pokerNum/k4/spriteFrame",
    JOKER_BIG = "img/pokerNum/dawang/spriteFrame",
    JOKER_SMALL = "img/pokerNum/xiaowang/spriteFrame",
    P_JOKER_BIG = "img/pokerNum/joker1/spriteFrame",
    P_JOKER_SMALL = "img/pokerNum/joker2/spriteFrame",
}

export default (bundlePkgName: string) => loopFiles(bundlePkgName, SpriteFrame, PokerSpriteFramePathDefine)