export enum PrefabDefine {
    SLOT_PANEL = "prefabs/slotPanel",
    ROLLER = "prefabs/roller",
    LOADER_PANEL = "prefabs/loaderPanel",
    FLY_BG = "prefabs/flyBg",
    // SUB_GAME = "prefabs/subGame",
    PARTICLE = "prefabs/Particle2D",
    DYNAMIC_NUMBER = "prefabs/dynamicNumber",
    DIALOG_WIN = "prefabs/dialogWin",
    PHOENIX_DIALOGWIN = "prefabs/node_phoenix_sgChoose",
    PHOENIX_TOTALBET = "prefabs/node_phoenix_totalBet",
    RULE_PANEL = "prefabs/rulePanel",
    TOAST = "prefabs/toast",
    SLOT_BG = "prefabs/slotBg",
    RESULT_SMALL = "prefabs/resultSmall",
}
